### ISSUE TITLE
Slash Command - p!unlock (misc.py)

### ISSUE THREAD

**Issue by alfadelta10010** [alfadelta10010/pesu-bot-2025#10]
Create a slash command for the channel unlock command.
Also ensure that the command shows up in discord's slash command menu.
You are free to update the discord-py-slash-command library from 3.0.3, provided you explain why.

**Comment by Vaarun-C** [comment]
Hey, can I be assigned to this :)

**Comment by alfadelta10010** [comment]
Can assign any two @MaNameEJeff, you already have two issues and we want updates as and when they come. There's a time cap of 30 mins on all 15 pts issues
