### ISSUE TITLE
Slash Command - p!restart (misc.py)

### ISSUE THREAD

**Issue by alfadelta10010** [alfadelta10010/pesu-bot-2025#15]
Create a slash command for the bot restart command.
Also ensure that the command shows up in discord's slash command menu.
You are free to update the discord-py-slash-command library from 3.0.3, provided you explain why.
Do not mess with the permissions, negative marks otherwise.

**Comment by Vaarun-C** [comment]
hey, can I be added to this :)

**Comment by alfadelta10010** [comment]
@MaNameEJeff Go for it!
