### ISSUE TITLE
Broken Slash Command - /pride (misc.py)

### ISSUE THREAD

**Issue by alfadelta10010** [alfadelta10010/pesu-bot-2025#17]
Fix the slash command for the Pride of PESU command, as it does not execute nor show up in the slash command menu.
You are free to update the discord-py-slash-command library from 3.0.3, provided you explain why.

**Comment by meghanagoru** [comment]
Hi, can this be assigned to me?

**Comment by alfadelta10010** [comment]
@gorumeg go for it!
