### ISSUE TITLE
Broken Slash Command - /confessbanuser (misc.py)

### ISSUE THREAD

**Issue by alfadelta10010** [alfadelta10010/pesu-bot-2025#19]
Fix the slash command for the command to ban a user from submitting confessions **based on username** (different from #18), as it does not execute nor show up in the slash command menu. It is visible in the code that the line exists, and has been commented out, as it does not work.
You are free to update the discord-py-slash-command library from 3.0.3, provided you explain why.

**Comment by Keshav1105** [comment]
Can i get this

**Comment by alfadelta10010** [comment]
@Keshav1105 done. Get on your bus and take a look at this
