### ISSUE TITLE
 In-app Documentation update - p!help (server.py)

### ISSUE THREAD

**Issue by alfadelta10010** [alfadelta10010/pesu-bot-2025#21]
Modify and format the help command in such a manner that upon invoking the command, the output descriptions look as follows:

> **Command Name**
> `command and aliases`
> 
> Simple description given
>
>‎‎‎‎‎‎

Do note the line breaks.
Additionally, remove segments of code that aren't mentioned in `server.py`, provided it doesn't break functionality. Test it and see :)

**Comment by Vaarun-C** [comment]
Hey can I be added to this :)

**Comment by alfadelta10010** [comment]
@MaNameEJeff Hi, can you please mention your name and SRN?

**Comment by alfadelta10010** [comment]
Assigned, start working! Remember to check the discord server

**Comment by Vaarun-C** [comment]
> @MaNameEJeff Hi, can you please mention your name and SRN?

Varun C, PES2UG21CS593.. sry for the weird account lol
