### ISSUE TITLE
Code clean-up (server.py)

### ISSUE THREAD

**Issue by alfadelta10010** [alfadelta10010/pesu-bot-2025#22]
Remove mentions of specific role IDs and move them to the top of the file as variables.
For example, Line [105](https://github.com/acmpesuecc/pesu-bot-2025/blob/ee8dae475eec0cc9a3c4b66c72c1df1271e8e0f5/cogs/server.py#L105) has "<@!931588180174589983>" mentioned in code, change the program such that the ID is mentioned through a variable, so that it can be replaced in multiple places at the same time.

**Comment by bcw117** [comment]
Created a pr for this, check #34

**Comment by tanishkapasarad** [comment]
can i be assigned to this? PES2UG21CS570

**Comment by NavinShrinivas** [comment]
yeah go ahead!

**Comment by alfadelta10010** [comment]
@tanishkapasarad any updates? it's been an hour, and the max time for a 25 pt issue is 40 mins.

**Comment by tanishkapasarad** [comment]
uploaded the pr
could not upload in time due to the events going on in sem hall

**Comment by Keshav1105** [comment]
can you assign if open
