### ISSUE TITLE
 Slash Command - p!ping (server.py)

### ISSUE THREAD

**Issue by alfadelta10010** [alfadelta10010/pesu-bot-2025#23]
Create a slash command for the ping response time command.
Also ensure that the command shows up in discord's slash command menu.
You are free to update the discord-py-slash-command library from 3.0.3, provided you explain why.

**Comment by Tree1527** [comment]
Could I be assigned this issue
Aditya Rajendra Shinde
PES2202200479

**Comment by alfadelta10010** [comment]
@Tree1527 still interested?

**Comment by BhaviniMadhuranath** [comment]
can i work on this?

**Comment by alfadelta10010** [comment]
@BhaviniMadhuranath go ahead

**Comment by Vaarun-C** [comment]
Hey can I work on this issue :)

**Comment by alfadelta10010** [comment]
Done
