### ISSUE TITLE
Update Verification for Semester (verification.py)

### ISSUE THREAD

**Issue by alfadelta10010** [alfadelta10010/pesu-bot-2025#26]
Change role settings to the following:
Sem-1: First Year Keeds
Sem-2: First Year Keeds
Sem-3: Second Year
Sem-4: Second Year
Sem-5: Seniors
Sem-6: Seniors
Sem-7: Seniors
Sem-8: Seniors

If code segments for specific semesters do not exists, duplicate pertinent code segments.

**Comment by rahul2001dewangan** [comment]
I would like to contribute. Please assign this to me.

**Comment by alfadelta10010** [comment]
Assigned. All the best!
