### ISSUE TITLE
Update verification to accept new data style (verification.py)

### ISSUE THREAD

**Issue by alfadelta10010** [alfadelta10010/pesu-bot-2025#28]
Upon referring `docs/sample_batch_list.txt` one sees that the "Name" data field was added in new data collection. The file `cogs/verification.py` hasn't been updated though, and using `dat[-1]` would collect incorrect information. 

**Task:** Change all occurrences of negative list indices to purely positive indices
`dat[-1]` -> `dat[9]`, for example

**Comment by Keshav1105** [comment]
Can i get this

**Comment by alfadelta10010** [comment]
@Keshav1105 Done. All the best!

**Comment by Keshav1105** [comment]
Shoudn't -1 go to 8
