### ISSUE TITLE
Script to convert CSV files to a database system (verification.py)

### ISSUE THREAD

**Issue by alfadelta10010** [alfadelta10010/pesu-bot-2025#30]
Currently, `cogs/verification.py` takes its data from a set of CSV files, example of which is given in `docs/sample_batch_list.txt`. We wish to transition to a database system. This is part 1 of that plan. (p2: #31)

What is expected: Create a script that can add data from CSV files to a SQLite 3 database.

**Comment by nik2203** [comment]
hi can i be assigned

**Comment by volt-roy** [comment]
hi pllsss assign this

**Comment by ramselvaraj** [comment]
hey can i work on this

**Comment by samarth777** [comment]
Hi can you assign this to me?

**Comment by alfadelta10010** [comment]
@samarth777 go ahead
