### ISSUE TITLE
Upgrade verification to extract data from SQLite database instead of CSV files

### ISSUE THREAD

**Issue by alfadelta10010** [alfadelta10010/pesu-bot-2025#31]
Currently, `cogs/verification.py` takes its data from a set of CSV files, example of which is given in `docs/sample_batch_list.txt`. We wish to transition to a database system. This is part 2 of that plan. (p1 #30)

What is expected: Modify `verification.py` to extract the required user data from an SQLite database into the `dat[]` variable

**Comment by nik2203** [comment]
hi, can i work on this?

**Comment by alfadelta10010** [comment]
Sure thing!

**Comment by nik2203** [comment]
question: do i assume that the sqlite server exists and work with that assumption or do i need to create it

**Comment by shaurya0148** [comment]
can i work on this??

**Comment by alfadelta10010** [comment]
Sorry @shaurya0148
