### ISSUE TITLE
Slash Command - p!count (misc.py)

### ISSUE THREAD

**Issue by alfadelta10010** [alfadelta10010/pesu-bot-2025#5]
Create a slash command for the member count command.
Also ensure that the command shows up in discord's slash command menu.
You are free to update the discord-py-slash-command library from 3.0.3, provided you explain why.

Do note it is a known issue where the bot prints two messages, with actual values in first message, and 0s for the values in the second message.

**Comment by Vaarun-C** [comment]
hey, can I be added to this :)
